### ISSUE TITLE
Option to load SVD files for devices that do not have packs 

### ISSUE THREAD

**Issue by tazbox** [gnu-mcu-eclipse/eclipse-plugins#130]
Hi Liviu,

I would like to congratulate you for developing and maintaining this plug-in. It's a big help for hobbyists worldwide.

I have an improvement suggestion related to Peripherals view. As not all silicon vendors publish CMSIS packs it would be nice to be able to load one or more SVD files (describing the core registers and the peripherals registers) even there is no device selected in C/C++ Build->Settings->Devices.

I'm willing to test this feature if you decide to implement it.

Kind regards,
Taz

**Comment by ilg-ul** [comment]
thank you @tazbox, I am considering a solution for this problem, but it'll take a while to be implemented.

**Comment by ilg-ul** [comment]
fixed in December 2017.

**Comment by ilg-ul** [comment]
included in v4.3.1-201801092051.
