### ISSUE TITLE
Error displayed when using J-Link and SWD

### ISSUE THREAD

**Issue by akuhtz** [gnu-mcu-eclipse/eclipse-plugins#212]
Hi,

I get an error when selecting SWD in the Debugger tab of the _GDB SEGGER J-Link Debugging_ configuration:
The reason is that in the launch configuration the following entry is generated with the interface in lowercase:
`
<stringAttribute key="ilg.gnuarmeclipse.debug.gdbjtag.jlink.gdbServerDebugInterface" value="swd"/>
`

Changing the value manually to uppercase makes the error disappear:
`
<stringAttribute key="ilg.gnuarmeclipse.debug.gdbjtag.jlink.gdbServerDebugInterface" value="SWD"/>
`

I'm using _SEGGER J-Link GDB Server V4.80_.

I think it comes from this definition:
https://github.com/gnu-mcu-eclipse/eclipse-plugins/blob/develop/bundles/ilg.gnumcueclipse.debug.gdbjtag.jlink/src/ilg/gnumcueclipse/debug/gdbjtag/jlink/preferences/DefaultPreferences.java#L25

... but mabe it's easier to just uppercase the value when it's written to the launch configuration:
https://github.com/gnu-mcu-eclipse/eclipse-plugins/blob/develop/bundles/ilg.gnumcueclipse.debug.gdbjtag.jlink/src/ilg/gnumcueclipse/debug/gdbjtag/jlink/Configuration.java#L121

**Comment by ilg-ul** [comment]
> I get an error when selecting SWD in the Debugger tab

where do you see this message? can you copy it, or make a window capture?

the default interface is swd, so this setting is widely used, but I've never seen any error message related to it.

**Comment by akuhtz** [comment]
When I start debugging (sorry I'm a newbie, can't describe better :-) ) I get the follwing error dialog:
![error-j-link](https://user-images.githubusercontent.com/1478878/27331426-b06cd9d0-55bd-11e7-9c5a-98e424cb66dc.png)

When I change the value manually to (uppercase) SWD the error disappears.

**Comment by akuhtz** [comment]
Hi Liviu,
I cannot reproduce it anymore :-( But I guess it was a problem with removing V6.10 and using V4.80 and not reboot.
I'll close this issue.

**Comment by ilg-ul** [comment]
ok, good luck with your projects!
