### ISSUE TITLE
Add openocd multi-core support

### ISSUE THREAD

**Issue by ilg-ul** [gnu-mcu-eclipse/eclipse-plugins#217]
openocd supports multi-code debug with multiple instances of the gdb server waiting on multiple ports.

the recommended setup uses a separate debug session that only starts openocd without gdb and several debug sessions that no loger start openocd but only gdb.

suggestion:

- add a check box to the Debugger tab to disable the gdb client

**Comment by flit** [comment]
Fyi, pyOCD will also support multicore once mbedmicro/pyOCD#325 is merged. The basic structure of one gdb server per core is the same.

**Comment by ilg-ul** [comment]
thank you, Chris.

**Comment by ilg-ul** [comment]
already fixed in 4.2.1
