### ISSUE TITLE
Global and Workspace Tools Paths not visible in Preferences

### ISSUE THREAD

**Issue by jonathan-archer** [gnu-mcu-eclipse/eclipse-plugins#227]
I have the same Issue as jtheires initially wrote here [https://github.com/gnu-mcu-eclipse/eclipse-plugins/issues/42](url) while checking the Preferences after installation of GNU MCU Plug in those sections do not exist. I got the PlugIn installed after manny tries with the Package 20170711-2049-gnumcueclipse-4.1.1-neon-3-linux.gtk.x86_64.tar.gz on my Ubuntu 16.04 with XFCE.
As shown in the attached images plugins allready installed.

![eclipse ver](https://user-images.githubusercontent.com/30837750/29084124-5344bbae-7c6b-11e7-8366-04d3497f0c6c.PNG)
![installed software](https://user-images.githubusercontent.com/30837750/29084125-53627d4c-7c6b-11e7-830f-c684dfa7d489.PNG)
![plug ins](https://user-images.githubusercontent.com/30837750/29084126-53689132-7c6b-11e7-8a19-0aa2d26e6dc3.PNG)
![ubuntu version](https://user-images.githubusercontent.com/30837750/29084127-536b7d7a-7c6b-11e7-94d8-4e35d90d250b.PNG)

**Comment by ilg-ul** [comment]
Check the new MCU preferences/properties page.

**Comment by ilg-ul** [comment]
did you find the new location of the pages?

**Comment by jonathan-archer** [comment]
Yes. Thank you for your help. Now it is working.
