### ISSUE TITLE
Leaving out the telnet port empty gives cryptic error.

### ISSUE THREAD

**Issue by AntonKrug** [gnu-mcu-eclipse/eclipse-plugins#242]
### Description

[cosmetic issue]
When a required field is left empty it returns a cryptic error message. 

### Steps to Reproduce

1. Setup generic project with the OpenOCD luncher.
2. Opening a debug launcher settings and deleting content from:
Debugger -> OpenOCD Setup -> Telnet port 
will cause getting a strange error dialog:

**Expected behaviour:**
Less cryptic error description or not allowing the user to put an empty string on a required field (instead of an InputStringField use NumberTextField, if that would help). 

**Actual behaviour:** 
"Update LCD" has encountered a problem.
An internal error has occurred.
An internal error has occurred.
  For input string: ""

![port](https://user-images.githubusercontent.com/30338596/31710130-07ea9602-b3ec-11e7-9079-6948ab8e79c4.png)

(googling this error points to workspace/maven issues which are not this case, so it can create even more confusion)

### Versions
* GNU MCU C/C++ OpenOCD Debugging 4.2.1
* Eclipse 4.6
* Java 1.8
* Windows 10 - 64bit

**Comment by ilg-ul** [comment]
I'll take a look.

**Comment by AntonKrug** [comment]
I was trying to find the text "Update LCD" in the repo and I couldn't find it, so my guess is that your method triggers exception which gets caught outside your plugin by something else.

**Comment by ilg-ul** [comment]
I don't remember this message either, so I guess you are right, the error comes from outside the plugin.

anyway, you are right, the plugin should validate the content of the gui input.

**Comment by AntonKrug** [comment]
I could be wrong but my guess would be that something like this causes an exception:

Integer.parseInt(“”);

Which is not caught by the plugin and gets propagated outside.

**Comment by ilg-ul** [comment]
yes, it might be so.

I don't have time to investigate now, so feel free to suggest a PR.

**Comment by ilg-ul** [comment]
fixed since v4.2.1-201711101735

**Comment by AntonKrug** [comment]
Excellent work :-)

**Comment by ilg-ul** [comment]
thank you.
