### ISSUE TITLE
Cannot see global tools paths in Eclipse Oxygen V4.7.0

### ISSUE THREAD

**Issue by Huubita** [gnu-mcu-eclipse/eclipse-plugins#261]
I install eclipse with gnu-arm on thumb drive, step-by-step from 2.2.1 to 2.2.1 in Mastering STM32, with:
-	Eclipse Oxygen 4.7.0 (June)
-	Plug in CDT (Full CDT Main Features)
-	GNU MCU Eclipse 4.2.1 [Name: GNU MCU Eclipse Plug-ins              Location: http://gnu-mcu-eclipse.netlify.com/v4-neon-updates
-	GCC ARM: gcc-arm-none-eabi-7-2017-q4-major-win32.exe
-	Build tools: gnu-mcu-eclipse-build-tools-2.9-20170629-1013-win64-setup.exe
-	OpenOCD: gnu-mcu-eclipse-openocd-0.10.0-5-20171110-1117-win64-setup.exe
All in folder, but I try to program “hello world” in C, then error “not found in PATH”. Open the Eclipse preferences , Window->Preferences go to C/C++->Build but CANNOT see global tools paths.

Tell me what to do more….

**Comment by ilg-ul** [comment]
> I install eclipse with gnu-arm on thumb drive, step-by-step from 2.2.1 to 2.2.1 in Mastering STM32, ... Window->Preferences go to C/C++->Build but CANNOT see global tools paths. ... Tell me what to do more….

the path setting pages were moved to the MCU group.
