### ISSUE TITLE
include some other folders?

### ISSUE THREAD

**Issue by jiapei100** [gnu-mcu-eclipse/eclipse-plugins#276]
@ilg-ul 

Hi, I created a **NEW** **BlinkLed** project, which is built successfully, with **NO** **ERROR** message. However, if I move these two files **BlinkLed.h** and **BlinkLed.c** into an independent folder named **BlinkLed**, and modify **main.c** accordingly to ensure the correct **PATH** of file **BlinkLed.h**. Afterwards, I **Build Project**, almost successful, but with an **ERROR** message 
` undefined reference to `blink_led_init'`

I wonder if I use this **GNU-MCU-Eclipse** plugin, will the project look on any created folder as a single library? I  mean, for instance, in my case above, will the Eclipse project build the folder **BlinkLed** with two files **BlinkLed.h** and **BlinkLed.c** into a library for the **main.c** to link finally? Otherwise, why there is an **ERROR** message **undefined reference** ?

Cheers
Pei

**Comment by ilg-ul** [comment]
did you tell Eclipse that the folder `led` contains source files?

**Comment by jiapei100** [comment]
@ilg-ul 
I did put two files **BlinkLed.h** and **BlinkLed.c** under the folder **BlinkLed** physically. I mean, I just did this **copy/move** using command line, and **refresh**ed it within **Eclipse IDE**.

How can I **tell** Eclipse that the folder contains source files? I just put one **.h** and one **.c** files under that particularly folder....

**Comment by ilg-ul** [comment]
Eclipse processes only files in folders defined as Source folders and ignores all other folders.

As homework, you have to discover how to define the Source folders.
