### ISSUE TITLE
SVD file type identification fails

### ISSUE THREAD

**Issue by ilg-ul** [gnu-mcu-eclipse/eclipse-plugins#286]
In certain conditions, SVD files are not recognised ("File format does not look like XML or JSON."), for example nrf52.svd for nRF52832_xxAA.

(the problem was reported by @PheeL79 at the end of https://github.com/gnu-mcu-eclipse/eclipse-plugins/issues/278).

**Comment by ilg-ul** [comment]
Fixed on 2018-04-03.

**Comment by PheeL79** [comment]
As a temporal workaround, you can convert the *.svd file and save it with "UTF-8" option in various text editors. After that the issue is gone (all the peripheral registers are visible and modifiable).
Thank you for the support!

**Comment by ilg-ul** [comment]
Yes, this can be a functional workaround.

Anyway, the v4.3.3 is planned for the next weekend.

**Comment by ilg-ul** [comment]
The 4.3.3.201804051758 pre-release is now available for testing from http://gnu-mcu-eclipse.netlify.com/v4-neon-updates-test.

**Comment by ilg-ul** [comment]
Fixed since 4.3.3.201804191501.
