### ISSUE TITLE
Hide the Devices tab for configurations not managed by GME

### ISSUE THREAD

**Issue by ilg-ul** [gnu-mcu-eclipse/eclipse-plugins#290]
The Devices tab contributed by the managedbuild.packs plug-in should not be visible for build configurations not managed by GME.

**Comment by ilg-ul** [comment]
To identify if the configuration is managed by GME, add a hidden option and test it (by SuperId("ilg.gnumcueclipse.managedbuild.cross.option.base.showDevicesTab")).

**Comment by ilg-ul** [comment]
Fixed on 2018-04-05.

**Comment by ilg-ul** [comment]
The 4.3.3.201804051758 pre-release is now available for testing from http://gnu-mcu-eclipse.netlify.com/v4-neon-updates-test.

**Comment by ilg-ul** [comment]
Fixed since 4.3.3.201804191501.

**Comment by ilg-ul** [comment]
Reopened due to #303.

**Comment by ilg-ul** [comment]
The requirement for a managed project was relaxed since 4.3.4, 2018-05-31.

**Comment by ilg-ul** [comment]
@nolange, please check the version from updates-test and let me know if the Devices tab is now visible in your setup.

**Comment by nolange** [comment]
Nope, still need to pick "ARM Cross GCC" as compiler, test-setup as specified in #295

**Comment by ilg-ul** [comment]
Yes, you need to use one of the known cross toolchains (ARM or RISC-V), but you no longer need a managed project.

**Comment by nolange** [comment]
I don't know what constitutes a "managed project", it worked for me before (using cmake4eclipse Builder). The only difference is that I don't get errors if the ARM/RISC-V Toolchains are not installed.
Whats new however is, that entering the toolchain settings page locks up eclipse for ~25 seconds.

**Comment by ilg-ul** [comment]
A "managed project" is a project that Eclipse knows in such detail that it is able to build automatically, either directly, using the now deprecated internal builder, or by generating the makefiles and invoking make.

**Comment by cmorty** [comment]
Sorry for the bugspam, but I wasn't able to find this out on my own: When will 4.3.4 be released and are there nightly builds?

**Comment by TM1234** [comment]
> are there nightly builds?

I don't know about nightly builds but see here about pre-release and experimental versions:

https://gnu-mcu-eclipse.github.io/plugins/download/#pre-release-versions

Hope this helps.

**Comment by ilg-ul** [comment]
4.3.4 will be released with the next Eclipse release, probably in July.

For now you can use it from the updates-test URL, as Tommy mentioned.

**Comment by cmorty** [comment]
OT: Thanks a lot. See #306  :)
