### ISSUE TITLE
Hide the Toolchains tab for non managed projects

### ISSUE THREAD

**Issue by ilg-ul** [gnu-mcu-eclipse/eclipse-plugins#291]
If the build configuration is not managed, hide the Toolchains tab.

**Comment by ilg-ul** [comment]
Fixed on 2018-04-05.

**Comment by ilg-ul** [comment]
The 4.3.3.201804051758 pre-release is now available for testing from http://gnu-mcu-eclipse.netlify.com/v4-neon-updates-test.

**Comment by ilg-ul** [comment]
Fixed since 4.3.3.201804191501.

**Comment by ilg-ul** [comment]
Reopened due to #303.

The condition is too restrictive, it must probably be only related to GME, not to unmanaged.

**Comment by sebastian-new** [comment]
Hello @ilg-ul . 

I tried this from #5 in 20180419-1818-gnumcueclipse-4.3.3-oxygen-3a-win32.win32.x86_64.zip

and it works. The settings tab allows you to assign device after you click on 'Generate Makefiles Automatically'

And this is for an unmanaged project.

**Comment by ilg-ul** [comment]
The requirement for a managed project was relaxed since 4.3.4, 2018-05-31.

**Comment by ilg-ul** [comment]
@nolange, please check the version from updates-test and let me know if the Toolchain tab is now visible in your setup.
