### ISSUE TITLE
Openings Settings takes long time and causes high CPU load

### ISSUE THREAD

**Issue by pikim** [gnu-mcu-eclipse/eclipse-plugins#307]
### Description
Opening the Settings takes a very long time (more than a minute) and consumes nearly 100% CPU power on one core.

### Steps to Reproduce
1. Open project Properties
2. Open C/C++ Build
3. Click on Settings

### Versions
- 20180419-1818-gnumcueclipse-4.3.3-oxygen-3a-linux.gtk.x86_64.tar.gz from you
- jre8-openjdk-headless-8.u172-2-x86_64 from Arch
- gcc-arm-none-eabi-7-2017-q4-major
- up-to-date Arch linux 
- ThinkPad T61 with Intel T9300, 4GB RAM and SSD

**Comment by ilg-ul** [comment]
hmmm... I've heard similar reports in the past, and they were, if I remember right, related to the Linux graphical environment, or the windows manager.

does it also happen for regular CDT projects? for example projects created with the Hello World project template using the Linux toolchain?

**Comment by TM1234** [comment]
> if I remember right, related to the Linux graphical environment, or the windows manager.

I may be mistaken but I have a recollection that switching from GTK3 to GTK2 rectified this problem. Try putting the following in your eclipse.ini and see if it helps:

```
--launcher.GTK_version
2
```

**Comment by ilg-ul** [comment]
yes, this is an old Linux workaround for Eclipse, it might still be valid.

**Comment by pikim** [comment]
> does it also happen for regular CDT projects? for example projects created with the Hello World project template using the Linux toolchain?

No, it doesn't happen. It opens instantly with a Linux project.

> Try putting the following in your eclipse.ini and see if it helps:
--launcher.GTK_version
2

That didn't work. I had to use ```export SWT_GTK3=0```. With GTK2 the problem doesn't appear.

**Comment by TM1234** [comment]
You might have to put --launcher=... in a particular place in the eclipse.ini file. I can't remember offhand 

If you don't see the problem with gtk2 then I think you're hitting a more general eclipse problem with gtk3 rather than something specific to the GNU MCU eclipse plugins.

**Comment by ilg-ul** [comment]
> Although the same Eclipse works with a Linux toolchain project?

Well, it is hard to tell for sure, but yes, Eclipse has lots of known problems, and some of them are related to rendering certain widgets on Linux. The Linux toolchain settings pages are relatively simple, and were obviously tested by the Eclipse CDT team thoroughly. The GME settings pages have more widgets, and apparently rendering them on Linux is problematic. 

The bad news is that there are little chances for this to be fixed any time soon; there are hundreds of Eclipse bugs in bugzilla and very few developers to address them.

**Comment by pikim** [comment]
OK, good to know. Thank you very much for your support! As long as Eclipse runs with GTK2 I can live with this solution.
