### ISSUE TITLE
QEMU Mac install instructions typo

### ISSUE THREAD

**Issue by BrendanSimon** [gnu-mcu-eclipse/eclipse-plugins#316]

**Comment by BrendanSimon** [comment]
The page `https://gnu-mcu-eclipse.github.io/qemu/install/` states the following:

`$ tar xvf ~/Downloads/gnu-mcu-eclipse-qemu-2.8.0-3-20180523-0703-osx.tgz`

however it should read as follows (based on archive in Releases):

`$ tar xvf ~/Downloads/gnu-mcu-eclipse-qemu-2.8.0-3-20180523-0703-macos.tgz`

**Comment by ilg-ul** [comment]
Ah, right, the naming convention was changed at a certain point.

I updated the page, it should propagate shortly.

Thank you for spotting the typo. If you find more, please let me know (https://github.com/gnu-mcu-eclipse/gnu-mcu-eclipse.github.io-source/issues).
