### ISSUE TITLE
Semihosting missing _EXFUN macro in GCC 7.3.x

### ISSUE THREAD

**Issue by jiapei100** [gnu-mcu-eclipse/eclipse-plugins#317]
Have NO idea what has happened ... it looks the GCC7.3.1-1.1.1 is buggy???
**~/opt/xPacks/@gnu-mcu-eclipse/arm-none-eabi-gcc/7.3.1-1.1.1/.content/bin**

```
../system/src/newlib/_syscalls.c:595:28: error: expected ')' before '(' token
 extern void _EXFUN(__sinit,(struct _reent*));
                            ^
../system/src/newlib/_syscalls.c: In function 'findslot':
../system/src/newlib/_syscalls.c:600:9: warning: implicit declaration of function '__sinit'; did you mean '__signed'? [-Wimplicit-function-declaration]
         __sinit (ptr);                          \
         ^
../system/src/newlib/_syscalls.c:613:3: note: in expansion of macro 'CHECK_INIT'
   CHECK_INIT(_REENT);
   ^~~~~~~~~~
make: *** [system/src/newlib/_syscalls.o] Error 1
system/src/newlib/subdir.mk:44: recipe for target 'system/src/newlib/_syscalls.o' failed

20:14:51 Build Failed. 3 errors, 1 warnings. (took 417ms)
```

**Comment by jiapei100** [comment]
Looks like if I have the following line commented:
`//extern void _EXFUN(__sinit,(struct _reent*));`

in file **_syscalss.c** (line 595).

Everything can be compiled successfully....

Is this a bug???

**Comment by ilg-ul** [comment]
I'll check and let you know. Can you confirm using the project generated by the F4 template?

**Comment by ilg-ul** [comment]
I confirm, the newlib headers in 7.3.x changed, and the _syscalls.c file does not compile.

Line 595 should read:

```c
extern void __sinit(struct _reent*);
```

**Comment by ilg-ul** [comment]
Fixed on 2018-08-27.

Please install the new beta version from http://gnu-mcu-eclipse.netlify.com/v4-neon-updates-experimental.

The problem was not specific to F429xx, it affected all semihosting tests.

**Comment by jiapei100** [comment]
Excellent !! That solved my problem.... Thank you @ilg-ul

**Comment by TM1234** [comment]
BTW - do you agree that the GME build scripts probably need to change to download and build binutils and gdb separately given what Jim says and how the riscv-gnu-tools repo is structured now? As opposed to downloading and building a "combined" riscv-binutils-gdb tarball? At least going forward?

Also - I may have mentioned this before but I tried to build 7.3 but the relevant tarballs are not on your github/archive. I guess you know this already?
________________________________
