### ISSUE TITLE
Unable to get debugger console when using eclipse version

### ISSUE THREAD

**Issue by pccdac** [gnu-mcu-eclipse/eclipse-plugins#326]

**Comment by pccdac** [comment]
Description
Unable to get debugger console using latest version of eclipse  (https://github.com/gnu-mcu-eclipse/org.eclipse.epp.packages/releases/download/v4.4.2-20180930-2018-09/20180930-0922-gnumcueclipse-4.4.2-2018-09-linux.gtk.x86_64.tar.gz).

Steps to Reproduce
-> Installed latest eclipse version
-> configured openocd and gdb in debugger configurations.
-> Debugger console is not working using this latest version.
But 
When i installed eclipse oxygen version https://github.com/gnu-mcu-eclipse/org.eclipse.epp.packages/releases/download/v4.4.1-20180721-o3a/20180721-1240-gnumcueclipse-4.4.1-oxygen-3a-linux.gtk.x86_64.tar.gz it is working.
Is there any problem with latest version of eclipse ?

Versions
Eclipse Oxygen
Linux
riscv64-unknown-elf-gcc version 7.2.0

**Comment by pccdac** [comment]
Description
Unable to get debugger console using latest version of eclipse (https://github.com/gnu-mcu-eclipse/org.eclipse.epp.packages/releases/download/v4.4.2-20180930-2018-09/20180930-0922-gnumcueclipse-4.4.2-2018-09-linux.gtk.x86_64.tar.gz).

Steps to Reproduce
-> Installed latest eclipse version
-> configured openocd and gdb in debugger configurations.
-> Debugger console is not working using this latest version.
But
When i installed eclipse oxygen version https://github.com/gnu-mcu-eclipse/org.eclipse.epp.packages/releases/download/v4.4.1-20180721-o3a/20180721-1240-gnumcueclipse-4.4.1-oxygen-3a-linux.gtk.x86_64.tar.gz it is working.
Is there any problem with latest version of eclipse ?

Versions
Eclipse Oxygen
Linux
riscv64-unknown-elf-gcc version 7.2.0

**Comment by ilg-ul** [comment]
> So the `${cross_prefix}` macro is not resolved when it's checking the version. 

aha. so you think the new Eclipse changed something in the way macros are processed, and `${cross_prefix}` is no longer resolved?

> Shouldn't the Configuration.getGdbServerCommand used on the macro executable to get the resolved actually executable before running it?

I don't know, I need to check the code. can you elaborate to help me get up to speed?

**Comment by AntonKrug** [comment]
I would say resolving it manually before calling Eclipse part should work on old and new Eclipse.

**Comment by ilg-ul** [comment]
right, but where do you suggest to add the resolving code?

**Comment by ilg-ul** [comment]
I confirm that by replacing the `${cross_prefix}gdb${cross_suffix}` with `arm-none-eabi-gdb`, the debugger console is visible even with 2018-09.

I'll try to investigate, but it might take some time, so any suggestions are welcome.

**Comment by ilg-ul** [comment]
FYI: https://bugs.eclipse.org/bugs/show_bug.cgi?id=541069

**Comment by ilg-ul** [comment]
CDT 9.5.5 fixed the problem. update your Eclipse and the Debugger Console should be fine.

**Comment by AntonKrug** [comment]
Should this be closed as the CDT update fixes it? Or you want to wait for your release to include it?

**Comment by ilg-ul** [comment]
My next release will probably be done after 2018-12 is out, so we'll probably leave the current release as it is, with the mention to perform an upgrade.

**Comment by AntonKrug** [comment]
The CDT update is painless now so there shouldn't a problem for users to upgrade if they need to. Or resolve the macro by hand if they do not want upgrade CDT.

**Comment by AntonKrug** [comment]
Actually there might be similar/related issues to this. The Debug Console view still is named without resolving `${cross_prefix}gdb${cross_suffix}`. And there is on the linux/windows terminal the message: `Unable to find full path for "${cross_prefix}gdb${cross_suffix}"`

**Comment by ilg-ul** [comment]
Yes, I know, we'll solve it at a later date.

**Comment by ilg-ul** [comment]
Well, they are not cosmetic, the CDT debug plug-ins somehow adapt to the GDB version; without the macro subtitution, they assume a very old version, so new features are not used. This may or may not affect embedded targets, I did not study the details.

**Comment by AntonKrug** [comment]
Oh, I was thinking that was happening before that it went to the worst implementation.

**Comment by ilg-ul** [comment]
Bug [541069](
https://bugs.eclipse.org/bugs/show_bug.cgi?id=541069) was fixed in CDT 9.5.5, released a few days ago, so the solution is to update your Eclipse to the latest available version.
