### ISSUE TITLE
Confused about the function of devices selection

### ISSUE THREAD

**Issue by hyf6661669** [gnu-mcu-eclipse/eclipse-plugins#337]
I'm using Eclipse for study:
```
Eclipse IDE for C/C++ Developers
Version: 2018-12 (4.10.0)
Build id: 20181214-0600
```
And my installed GNU ARM C/C++ Packs (Experimental) version is ```2.2.2.201704251808```.

When I try to create a new STM32F0 project, in this page I use default settings for RAM and FLASH:
![default settings](https://user-images.githubusercontent.com/18757974/51155070-39d43f80-18b1-11e9-8ac9-c066ed61444c.jpg)
So I can see that the generated file ```mem.ld``` is in accordance with the settings:
![mem_ld](https://user-images.githubusercontent.com/18757974/51155198-af401000-18b1-11e9-9840-7ab197313f78.png)
But if I open the project options and try to chosse a particular device,  STM32F098CC for example:
![device selection](https://user-images.githubusercontent.com/18757974/51155373-3db49180-18b2-11e9-8126-73706e75c286.png)
The RAM size of STM32F098CC is 32KB, and the ROM size of STM32F098CC is 256KB, which is not the same as the settings I used when I created the project. After I click ```Apply and Close```, the file ```mem.ld``` is not changed. 

I have already read this page:
https://gnu-mcu-eclipse.github.io/eclipse/project/assign-device/
It says:
```
Accompanying the device there is also a set of definition for the memory map, which will be used in a future release to automatically generate the linker scripts.
```
Does it means that, at present, I have to modify the ```mem.ld``` manually if I want to write programs for different device?

**Comment by ilg-ul** [comment]
> Does it means that, at present, I have to modify the mem.ld manually if I want to write programs for different device?

That's correct. 

Both the text in the window and the documentation mention this. Which part needs more explanations?

For further quesion and support, please use the project forum.
