### ISSUE TITLE
post-build script

### ISSUE THREAD

**Issue by esaulenka** [gnu-mcu-eclipse/eclipse-plugins#350]
Please, change makefile generator.

I am using post-build script to convert output hex-file to our own format.
Now `make` working in next order:
- create elf-file
- run post-build
- convert elf -> hex

But in this way my script handles old version of hex-file, remaining from previous run.
Please, create dependency that `post-build` target requires `secondary-outputs`

**Comment by ilg-ul** [comment]
Unfortunatelly the post-build step is handled by CDT itself, not the GME plug-ins.

I suggest you simply disable the current conversion step (in the Toolchain tab) and use only your custom script.

**Comment by esaulenka** [comment]
Ok, thanks!
I came up the same way: first i run objcopy and then process output hex.

But this method looks ugly...
```
    import subprocess
    in_file = os.path.splitext(out_file)[0] + '.elf'
    in_file = '"' + in_file + '"'
    out_file = '"' + out_file + '"'
    cmd = 'arm-none-eabi-objcopy -O ihex ' + in_file + ' ' + out_file
    res = subprocess.call(cmd, shell=not IsRunOnWindows())
    if res: exit()
```
