### ISSUE TITLE
Plugins not available for MCUXpresso IDE 11.0.1

### ISSUE THREAD

**Issue by miguel9554** [gnu-mcu-eclipse/eclipse-plugins#365]
The newest version of MCUXpresso IDE (11.0.1) is not able to install plugins from http://gnuarmeclipse.sourceforge.net/updates. The IDE gives the following error:

```
An error occurred while collecting items to be installed
session context was:(profile=DefaultProfile, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: binary,MCUXpressoIDE.executable.gtk.linux.x86_64,11.0.0.201908271452
```

Previous version 11.0.0 allows it with no problem. I don't know if it's a bad backward compatibility implemented by NXP or a bad configuration on the sourceforge server

**Comment by ilg-ul** [comment]
Are you sure that this is a GME plug-ins bug?

**Comment by miguel9554** [comment]
I solved the issue, it was a problem with the IDE. Thanks for answering, I will change the install site for future installs.

**Comment by ilg-ul** [comment]
> it was a problem with the IDE

Could you document the issue, and the solutions, to help others encountering the same problem?
