### ISSUE TITLE
pyOCD Debugger launch config tab shouldn't populate targets combobox with static list

### ISSUE THREAD

**Issue by sukidog** [gnu-mcu-eclipse/eclipse-plugins#82]
[fix on the way]
The implementation invokes the pyOCD gdbserver to determine what boards and processors ("targets") it supports and makes those choices available in the Debugger tab. However, if first populates the processor combobox with a static default list. That's misleading and ultimately can do more harm than good.

**Comment by ilg-ul** [comment]
For the pyOCD plug-in (currently not included in the public release), please coordinate with Chris @flit, he added it and he will maintain it.

**Comment by sukidog** [comment]
We work together. (He is about 100' down the hall from me). He's given me write access to his repository. I'll be submitting fixes, but first creating bugs for them. Expect most pyOCD plug-in activity to come from me.

**Comment by ilg-ul** [comment]
Great, then both of you will maintain the plug-in! :-)

**Comment by ilg-ul** [comment]
was this issue solved?

**Comment by flit** [comment]
@ilg-ul This issue has been fixed.

**Comment by ilg-ul** [comment]
great, please submit the pull requests.

**Comment by flit** [comment]
Sorry, I meant that the fix has already been merged and you can close this issue. (Same with #83.)
