### ISSUE TITLE
[CMSIS-Pack] Nordic nRF51 and nRF52 series devices not found

### ISSUE THREAD

**Issue by vidarbe** [gnu-mcu-eclipse/eclipse-plugins#92]
Hi,

First, thanks for this great plug-in! It has made it much easier to integrate J-link debugging in Eclipse as well as improving integration with arm-none-eabi. 

Only problem I have is that if I install device family pack version 8.3.2 or later the device selection become empty in the project settings. Comparing the 8.3.1 against 8.3.2 the only noticeable difference I could find was that 'date' was added to the release version on all the following releases that didn't work:

```
 <release version="8.3.2" date="2015-12-16">
Date: 16.12.2015 Updated release version to adapt to MDK version.
</release>
<release version="8.3.1">
Date: 13.11.2015 Updated release version to adapt to MDK version.
</release>
```

Also, from the packs log I can  see that it tries to parse  NordicSemiconductor.nRF_DeviceFamilyPack.8.5.0.pdsc, which doesn't exist:

> Parsing cached PDSC file "C:\Eclipse_tutorial\eclipse-cpp-mars-1-win32-x86_64\eclipse\Packages.cache\NordicSemiconductor.nRF_DeviceFamilyPack.8.5.0.pdsc"...
> Error: C:\Eclipse_tutorial\eclipse-cpp-mars-1-win32-x86_64\eclipse\Packages.cache\NordicSemiconductor.nRF_DeviceFamilyPack.8.5.0.pdsc (The system cannot find the file specified), file: NordicSemiconductor.nRF_DeviceFamilyPack.8.5.0.pdsc

Instead it should look for [nRF_DeviceFamilyPack.pdsc](http://developer.nordicsemi.com/nRF5_SDK/pieces/nRF_DeviceFamilyPack/NordicSemiconductor.nRF_DeviceFamilyPack.pdsc) I think. Manually renaming nRF_DeviceFamilyPack.pdsc to nRF_DeviceFamilyPack.8.5.0.pdsc and adding it to the .cache directory does solve the problem though. 

Thanks, 
Vidar

**Comment by ilg-ul** [comment]
please try the latest beta from updates-test, I guess this issue was already solved.
